spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.164/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
  port: 80
wechat:
  mpAppId: wx16375f704562466e
  mpAppsecret: 87fdce3c1246908dd3d7ee539032bff9
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/wexin_cert/h5.p12
  notifyUrl: http://hornyun.natapp1.cc/sell/pay/notify


#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: D:\sell.log
#  level:
#    com.imooc.*: debug